'use client';
import { createContext, useContext, useState, useEffect } from 'react';

export const themes = {
  sunny: {
    id: 'sunny',
    name: '☀️ Nắng Hè',
    description: 'Tươi sáng & năng động',
    preview: ['#FF6B35', '#FFD23F', '#ffffff'],
    vars: {
      '--header-bg': '#FF6B35',
      '--header-text': '#ffffff',
      '--header-link': 'rgba(255,255,255,0.85)',
      '--header-link-hover': '#ffffff',
      '--header-accent': '#FFD23F',
      '--header-mobile-bg': '#FF6B35',
      '--page-bg': '#fffdf7',
      '--card-bg': '#ffffff',
      '--card-border': '#ffe5d0',
      '--primary': '#FF6B35',
      '--primary-hover': '#e55a25',
      '--primary-shadow': 'rgba(255,107,53,0.35)',
      '--accent': '#FFD23F',
      '--text-heading': '#7c2d12',
      '--text-body': '#92400e',
      '--text-muted': '#b45309',
      '--footer-bg': '#FF6B35',
      '--footer-text': '#ffffff',
      '--footer-muted': 'rgba(255,255,255,0.7)',
      '--footer-accent': '#FFD23F',
      '--hero-from': '#FF6B35',
      '--hero-via': '#f97316',
      '--hero-to': '#FFD23F',
      '--hero-text': '#ffffff',
      '--hero-sub': 'rgba(255,255,255,0.85)',
      '--btn-outline-border': 'rgba(255,255,255,0.5)',
      '--stats-bg': '#FFD23F',
      '--stats-text': '#7c2d12',
      '--stats-sub': 'rgba(124,45,18,0.7)',
      '--cta-bg': '#FF6B35',
      '--accent-line': '#FFD23F',
      '--scrollbar': '#ffb899',
    },
  },
  ocean: {
    id: 'ocean',
    name: '🌊 Đại Dương',
    description: 'Mát mẻ & bình yên',
    preview: ['#0ea5e9', '#38bdf8', '#e0f7ff'],
    vars: {
      '--header-bg': '#0369a1',
      '--header-text': '#ffffff',
      '--header-link': 'rgba(255,255,255,0.85)',
      '--header-link-hover': '#ffffff',
      '--header-accent': '#38bdf8',
      '--header-mobile-bg': '#0369a1',
      '--page-bg': '#f0faff',
      '--card-bg': '#ffffff',
      '--card-border': '#bae6fd',
      '--primary': '#0ea5e9',
      '--primary-hover': '#0284c7',
      '--primary-shadow': 'rgba(14,165,233,0.35)',
      '--accent': '#38bdf8',
      '--text-heading': '#0c4a6e',
      '--text-body': '#075985',
      '--text-muted': '#0369a1',
      '--footer-bg': '#0369a1',
      '--footer-text': '#ffffff',
      '--footer-muted': 'rgba(255,255,255,0.7)',
      '--footer-accent': '#38bdf8',
      '--hero-from': '#0c4a6e',
      '--hero-via': '#0369a1',
      '--hero-to': '#0ea5e9',
      '--hero-text': '#ffffff',
      '--hero-sub': 'rgba(255,255,255,0.85)',
      '--btn-outline-border': 'rgba(255,255,255,0.5)',
      '--stats-bg': '#0ea5e9',
      '--stats-text': '#ffffff',
      '--stats-sub': 'rgba(255,255,255,0.8)',
      '--cta-bg': '#0369a1',
      '--accent-line': '#38bdf8',
      '--scrollbar': '#7dd3fc',
    },
  },
  sakura: {
    id: 'sakura',
    name: '🌸 Hoa Anh Đào',
    description: 'Ngọt ngào & dễ thương',
    preview: ['#ec4899', '#f9a8d4', '#fdf2f8'],
    vars: {
      '--header-bg': '#be185d',
      '--header-text': '#ffffff',
      '--header-link': 'rgba(255,255,255,0.85)',
      '--header-link-hover': '#ffffff',
      '--header-accent': '#f9a8d4',
      '--header-mobile-bg': '#be185d',
      '--page-bg': '#fdf4ff',
      '--card-bg': '#ffffff',
      '--card-border': '#fce7f3',
      '--primary': '#ec4899',
      '--primary-hover': '#db2777',
      '--primary-shadow': 'rgba(236,72,153,0.35)',
      '--accent': '#f9a8d4',
      '--text-heading': '#831843',
      '--text-body': '#9d174d',
      '--text-muted': '#be185d',
      '--footer-bg': '#be185d',
      '--footer-text': '#ffffff',
      '--footer-muted': 'rgba(255,255,255,0.7)',
      '--footer-accent': '#f9a8d4',
      '--hero-from': '#831843',
      '--hero-via': '#be185d',
      '--hero-to': '#ec4899',
      '--hero-text': '#ffffff',
      '--hero-sub': 'rgba(255,255,255,0.85)',
      '--btn-outline-border': 'rgba(255,255,255,0.5)',
      '--stats-bg': '#ec4899',
      '--stats-text': '#ffffff',
      '--stats-sub': 'rgba(255,255,255,0.8)',
      '--cta-bg': '#be185d',
      '--accent-line': '#f9a8d4',
      '--scrollbar': '#f9a8d4',
    },
  },
  forest: {
    id: 'forest',
    name: '🌿 Rừng Xanh',
    description: 'Tươi mát & tự nhiên',
    preview: ['#16a34a', '#4ade80', '#f0fdf4'],
    vars: {
      '--header-bg': '#15803d',
      '--header-text': '#ffffff',
      '--header-link': 'rgba(255,255,255,0.85)',
      '--header-link-hover': '#ffffff',
      '--header-accent': '#4ade80',
      '--header-mobile-bg': '#15803d',
      '--page-bg': '#f0fdf4',
      '--card-bg': '#ffffff',
      '--card-border': '#bbf7d0',
      '--primary': '#16a34a',
      '--primary-hover': '#15803d',
      '--primary-shadow': 'rgba(22,163,74,0.35)',
      '--accent': '#4ade80',
      '--text-heading': '#14532d',
      '--text-body': '#166534',
      '--text-muted': '#15803d',
      '--footer-bg': '#15803d',
      '--footer-text': '#ffffff',
      '--footer-muted': 'rgba(255,255,255,0.7)',
      '--footer-accent': '#4ade80',
      '--hero-from': '#14532d',
      '--hero-via': '#15803d',
      '--hero-to': '#16a34a',
      '--hero-text': '#ffffff',
      '--hero-sub': 'rgba(255,255,255,0.85)',
      '--btn-outline-border': 'rgba(255,255,255,0.5)',
      '--stats-bg': '#16a34a',
      '--stats-text': '#ffffff',
      '--stats-sub': 'rgba(255,255,255,0.8)',
      '--cta-bg': '#15803d',
      '--accent-line': '#4ade80',
      '--scrollbar': '#86efac',
    },
  },
  violet: {
    id: 'violet',
    name: '💜 Tím Mộng Mơ',
    description: 'Bí ẩn & sáng tạo',
    preview: ['#7c3aed', '#a78bfa', '#f5f3ff'],
    vars: {
      '--header-bg': '#6d28d9',
      '--header-text': '#ffffff',
      '--header-link': 'rgba(255,255,255,0.85)',
      '--header-link-hover': '#ffffff',
      '--header-accent': '#a78bfa',
      '--header-mobile-bg': '#6d28d9',
      '--page-bg': '#faf8ff',
      '--card-bg': '#ffffff',
      '--card-border': '#ede9fe',
      '--primary': '#7c3aed',
      '--primary-hover': '#6d28d9',
      '--primary-shadow': 'rgba(124,58,237,0.35)',
      '--accent': '#a78bfa',
      '--text-heading': '#4c1d95',
      '--text-body': '#5b21b6',
      '--text-muted': '#6d28d9',
      '--footer-bg': '#6d28d9',
      '--footer-text': '#ffffff',
      '--footer-muted': 'rgba(255,255,255,0.7)',
      '--footer-accent': '#a78bfa',
      '--hero-from': '#4c1d95',
      '--hero-via': '#6d28d9',
      '--hero-to': '#7c3aed',
      '--hero-text': '#ffffff',
      '--hero-sub': 'rgba(255,255,255,0.85)',
      '--btn-outline-border': 'rgba(255,255,255,0.5)',
      '--stats-bg': '#7c3aed',
      '--stats-text': '#ffffff',
      '--stats-sub': 'rgba(255,255,255,0.8)',
      '--cta-bg': '#6d28d9',
      '--accent-line': '#a78bfa',
      '--scrollbar': '#c4b5fd',
    },
  },
  classic: {
    id: 'classic',
    name: '🚦 Giao Thông',
    description: 'Chuyên nghiệp & uy tín',
    preview: ['#1a2b4a', '#f97316', '#f8fafc'],
    vars: {
      '--header-bg': '#1a2b4a',
      '--header-text': '#ffffff',
      '--header-link': 'rgba(255,255,255,0.85)',
      '--header-link-hover': '#ffffff',
      '--header-accent': '#f97316',
      '--header-mobile-bg': '#1a2b4a',
      '--page-bg': '#f8fafc',
      '--card-bg': '#ffffff',
      '--card-border': '#e2e8f0',
      '--primary': '#f97316',
      '--primary-hover': '#ea6c0d',
      '--primary-shadow': 'rgba(249,115,22,0.35)',
      '--accent': '#f59e0b',
      '--text-heading': '#1a2b4a',
      '--text-body': '#334155',
      '--text-muted': '#64748b',
      '--footer-bg': '#1a2b4a',
      '--footer-text': '#ffffff',
      '--footer-muted': 'rgba(255,255,255,0.6)',
      '--footer-accent': '#f97316',
      '--hero-from': '#0f1d33',
      '--hero-via': '#1a2b4a',
      '--hero-to': '#1e3a5f',
      '--hero-text': '#ffffff',
      '--hero-sub': 'rgba(255,255,255,0.8)',
      '--btn-outline-border': 'rgba(255,255,255,0.3)',
      '--stats-bg': '#f97316',
      '--stats-text': '#ffffff',
      '--stats-sub': 'rgba(255,255,255,0.8)',
      '--cta-bg': '#1a2b4a',
      '--accent-line': '#f97316',
      '--scrollbar': '#cbd5e1',
    },
  },
};

const ThemeContext = createContext(null);

export function ThemeProvider({ children }) {
  const [themeId, setThemeId] = useState('sunny');

  useEffect(() => {
    const saved = localStorage.getItem('atgt-theme');
    if (saved && themes[saved]) setThemeId(saved);
  }, []);

  useEffect(() => {
    const theme = themes[themeId];
    if (!theme) return;
    const root = document.documentElement;
    Object.entries(theme.vars).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });
    localStorage.setItem('atgt-theme', themeId);
  }, [themeId]);

  return (
    <ThemeContext.Provider value={{ themeId, setThemeId, themes }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  return useContext(ThemeContext);
}
